### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by wareya** [wareya/Material-Basher#1]
- [ ] 3-in-1 export
- [ ] UV rotation...?
- [ ] lighting removal: normal-mapped lighting
- [ ] lighting removal: gradients
- [ ] lighting removal: "affect light" system for ao removal
- [ ] ability to load specific pre-existing materials (e.g. if the user already has a good depth texture)
- [x] settings save/load via json (versioned with warnings for old settings)
- [x] ability to store things in diffuse alpha and normal map blue/alpha channels
- [x] option to disable wrapping
- [x] append .png to export filename if it's missing
- [x] expand AO bias range by a lot
- [x] config reset-to-default button
- [x] fix material preview not updating until modifying the tab's material
- [x] tga export
- [x] remember imported filename and save with a suffix

----

- ~~paste image~~ (not possible without adding a gdnative extension)
- ~~option for height/displacement instead of depth~~ (godot's depth shader can't accurately do height and depth at the same time)
